---
#- name: send email
#  become: yes
#  become_user: root
#  cron:
#    name: send email
#    backup: yes
#    minute: "*/5"
#    job: "flock -xn /var/tmp/send_email.lock -c 'cd {{ django_base_dir }}; /usr/bin/python3.7 -m pipenv run python manage.py send_email  >> {{ log_dir }}crontab.log 2>&1'"
