---
- name: generate systemd config
  template:
    src: templates/systemd
    dest: "/lib/systemd/system/{{service_name}}.service"
  become: yes
  become_user: root


- name: force systemd to reread configs
  become: yes
  become_user: root
  systemd:
    daemon_reload: yes