---

- name: check if {{ inventory_hostname }}:{{ deploy_project_dir }} exist
  stat: path="{{ deploy_project_dir }}"
  register: stat_result
  become: true
  become_user: root

- name: create {{ inventory_hostname }}:{{ deploy_project_dir }} if not exist
  file:
    path: "{{ deploy_project_dir }}"
    state: directory
  when: not stat_result.stat.exists
  become: true
  become_user: root

- name: get timestamp
  when: stat_result.stat.exists
  shell: "date +%Y-%m-%d_%Hh%Mm%Ss_%Z"
  register: timestamp
  changed_when: false

- name: backup {{ inventory_hostname }}:{{ deploy_project_dir }}
  when: stat_result.stat.exists
  command: "cp -r {{ deploy_project_dir }} {{ project_name }}_{{ timestamp.stdout }}"
  args:
    chdir: "{{ deploy_project_dir }}/../"
  become: true
  become_user: root