---
# 1. Compose nginx config file
- name: create nginx config file "{{nginx_conf_file}}"
  become: yes
  become_user: root
  template:
    src: templates/nginx_conf
    dest: "{{nginx_conf_file}}"

# 2. Sync SSL to destination host
- name: sync from "{{ temp_dir }}/{{server_host}}/" to "/etc/nginx/ssl/{{server_host}}"
  when: update_nginx
  become: true
  become_user: root
  synchronize:
    partial: yes
    recursive: yes
    dest: "/etc/nginx/ssl/{{server_host}}"
    src: "{{ temp_dir }}/{{server_host}}/"
    delete: no
    use_ssh_args: yes

# 3. Reload Nginx
- name: test nginx config
  become: true
  become_user: root
  shell: "nginx -t"

- name: reload nginx config
  become: true
  become_user: root
  shell: "nginx -s reload"