---
- name: checkout "{{git_repo}}" "{{git_branch}}" to "{{ code_temp_dir }}"
  run_once: true
  delegate_to: 127.0.0.1
  local_action: git
  args:
    repo: "{{git_repo}}"
    accept_hostkey: True
    recursive: yes
    remote: origin
    dest: "{{ code_temp_dir }}"
    version: "{{git_branch}}"
    update: yes

- name: create "{{ dist_dir }}"
  run_once: true
  delegate_to: 127.0.0.1
  file:
    path: "{{ dist_dir }}"
    state: directory

- name: synchronize from "{{ code_temp_dir }}/" to "{{ dist_dir }}"
  run_once: true
  delegate_to: 127.0.0.1
  synchronize:
    partial: yes
    recursive: yes
    dest: "{{ dist_dir }}"
    src: "{{ code_temp_dir }}/"
    use_ssh_args: yes