---
# virtual_env: group variable
- name: add certbot repository
  when: not has_certificate
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  become: yes
  become_user: root

- name: install python-certbot-nginx
  when: not has_certificate
  package:
    name: python-certbot-nginx
    state: present
  become: yes
  become_user: root

- name: install python 3.6
  package:
    name: "{{item}}"
    state: present
  become: yes
  become_user: root
  with_items:
    - python3
    - python3.7
    - python3-dev
    - python3-pip
    - libssl-dev
    - libmysqlclient-dev
    - gettext

- name: pip install pipenv
  command: python3 -m pip install pipenv
  become: yes
  become_user: root

- name: install python packages {% if env == "dev"%}-d{% endif %}
  become: true
  become_user: root
  command: python3 -m pipenv sync {% if env == "dev"%}-d{% endif %} --sequential
  args:
    chdir: "{{ deploy_project_dir }}"
