---
# virtual_env: group variable
- name: generate gunicorn config
  template:
    src: templates/gunicorn.template.py
    dest: "{{deploy_project_dir}}/deploy/gunicorn.py"
  become: yes
  become_user: root

- name: touch gunicorn log "{{errorlog}}"
  become: yes
  become_user: root
  file:
    path: "{{errorlog}}"
    state: touch

- name: register start command "/usr/bin/python3 -m pipenv run gunicorn -c {{deploy_project_dir}}/deploy/gunicorn.py {{django_default_app}}.wsgi"
  set_fact:
    start_command: "/usr/bin/python3 -m pipenv run gunicorn -c {{deploy_project_dir}}/deploy/gunicorn.py {{django_default_app}}.wsgi"