---
- name: create nginx config file "{{nginx_conf_file}}"
  when: has_certificate
  become: yes
  become_user: root
  template:
    src: templates/nginx_conf
    dest: "{{nginx_conf_file}}"

- name: create nginx config file "{{nginx_conf_file}}"
  when: not has_certificate
  become: yes
  become_user: root
  template:
    src: templates/nginx_80_conf
    dest: "{{nginx_conf_file}}"

- name: create nginx config file "{{nginx_conf_file}}"
  when: not has_certificate
  become: yes
  become_user: root
  template:
    src: templates/nginx_80_conf
    dest: "{{nginx_conf_file}}"

- name: using certbot to update config file
  when: not has_certificate
  become: true
  become_user: root
  shell: "certbot --nginx --non-interactive --agree-tos --redirect --domains {{server_host}} --email doanngocbao@gmail.com"

- name: renew letencrypt certificate
  when: not has_certificate
  become: yes
  become_user: root
  cron:
    name: renew letencrypt certificate
    backup: yes
    hour: 0
    minute: 0
    job: "certbot renew > /dev/null"

- name: test nginx config
  become: true
  become_user: root
  shell: "nginx -t"

- name: reload nginx config
  become: true
  become_user: root
  shell: "nginx -s reload"