---
- name: register stat "{{ dist_dir }}"
  delegate_to: localhost
  stat:
    path: "{{ dist_dir }}"
  register: dist_path

- name: check "{{ dist_dir }}"
  when: dist_path.stat.exists != True or dist_path.stat.isdir != True
  fail:
    msg: "Check {{ dist_dir }} failed."

- name: sync from "{{ dist_dir }}" to "{{ deploy_project_dir }}"
  become: true
  become_user: root
  synchronize:
    delete: yes
    partial: yes
    recursive: yes
    dest: "{{ deploy_project_dir }}"
    src: "{{ dist_dir }}"
    use_ssh_args: yes