---
- name: whitelist load balancer
  blockinfile:
    path: "{{ iptables_config_file }}"
    block: |
      -A INPUT -s {{ hostvars[item]['private_ip'] }}  -p tcp --dport {{ server_port }} -j ACCEPT
    marker: "# {mark} {{project_name}} {{ item }}"
    insertafter: ":OUTPUT\\s*ACCEPT\\s*\\[\\d+:\\d+\\]"
    create: no
    mode: 0644
    owner: root
    state: present
  with_items: "{{ groups['load_balancer'] }}"
  when: groups['load_balancer']
  become: true
  become_user: root

- name: restart iptables
  become: true
  become_user: root
  service:
    name: "iptables"
    state: restarted